### PR TITLE
Updated project with latest changes from Sendgrid + updated Godeps

### PR DESCRIPTION
**Pull request by iambrosi**
The new dependency VividCortex/rest has been added to Godeps file, along with a small change to make sure it uses our fork and not Sendgrid's(which won't be installed by _jd_).

### CODE REVIEW

**Review by gkristic-vc — CHANGES_REQUESTED** [review]
Missing dependency update in [this](https://github.com/VividCortex/sendgrid-go/blob/a8598a4c4c6b67af0a5103240edc1fe53cb9eb77/helpers/inbound/inbound.go#L16) line for package code and [these](https://github.com/VividCortex/sendgrid-go/blob/a8598a4c4c6b67af0a5103240edc1fe53cb9eb77/sendgrid_test.go#L18-L19) two for tests. There are others in the examples, but I'm not concerned about those.

**Comment by gkristic-vc** [comment]
Just noticed that the commit referenced [here](https://github.com/VividCortex/sendgrid-go/blob/a8598a4c4c6b67af0a5103240edc1fe53cb9eb77/Godeps#L2) is not in master. We should merge that one and update the Godeps here.

**Comment by iambrosi** [comment]
@gkristic-vc Now that https://github.com/VividCortex/rest/pull/1 has been merged, the [commit](https://github.com/VividCortex/rest/commit/80b39aaf5a30edab5bf2f99d56052abe01a0d41d) can be found in master.

**Comment by gkristic-vc** [comment]
How about pointing to the [merge commit](https://github.com/VividCortex/rest/commit/60416b8f5c82e5992471f479d98a9d911741a277)?

**Review by gkristic-vc — APPROVED** [review]

**Comment by iambrosi** [comment]
Thanks Gus!

**Pull request merged**
